Fix indentation in YAML.

diff --git a/.github/workflows/deploy_docs.yml b/.github/workflows/deploy_docs.yml
--- a/.github/workflows/deploy_docs.yml
+++ b/.github/workflows/deploy_docs.yml
@@ -8,104 +8,105 @@ run-name: Deploy docs for branch/release `${{ github.ref }}` to GitHub Pages.
 
 # List of event types that trigger the deploying of Rustdocs.
 on:
-    # 1. Receiving a push to any branch.
-    push:
+  # 1. Receiving a push to any branch.
+  push:
 
-    # 2. Releasing a prerelease or stable release.
-    release:
-        types:
-            - prereleased
-            - released
+  # 2. Releasing a prerelease or stable release.
+  release:
+    types:
+      - prereleased
+      - released
 
 jobs:
-    build_docs:
-        name: Build rustdocs
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout updated `hotstuff_rs` ref 
-              uses: actions/checkout@v4
+  build_docs:
+    name: Build rustdocs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout updated `hotstuff_rs` ref 
+        uses: actions/checkout@v4
+    
+      - name: Install Rust toolchain
+        uses: actions-rust-lang/setup-rust-toolchain@v1 
+
+      - name: Generate complete rustdocs 
+        run: cargo doc --document-private-items --no-deps 
+
+      - name: Upload rustdocs as `complete_docs` artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: complete_docs
+          path: target/doc/
+
+  push_docs:
+    name: Push rustdocs to `hotstuff_rs_docs` repository
+    runs-on: ubuntu-latest
+    needs: build_docs
+    steps:
+      - name: Checkout latest `hotstuff_rs_docs`
+        uses: actions/checkout@v4
+        with:
+          repository: parallelchain-io/hotstuff_rs_docs
+          fetch-depth: 0
+          token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}
+
+      - name: Compute path to the subfolder the docs should be placed in 
+        id: compute_subfolder_path
+        run: |
+          subfolder_path=$GITHUB_REF_TYPE/$GITHUB_REF_NAME/
+          echo "subfolder_path=$subfolder_path" >> $GITHUB_OUTPUT
+        env:
+            GITHUB_REF_TYPE: "${{ github.ref_type }}"
+            GITHUB_REF_NAME: "${{ github.ref_name }}"
+
+      - name: Prepare the subfolder
+        run: |
+          if [ -d $SUBFOLDER_PATH ]; then
+              echo "Subfolder `$SUB_FOLDER_PATH` already exists, clearing its contents"
+              rm -rf "${SUBFOLDER_PATH:?}/"*
+          else
+              echo "Subfolder `$SUBFOLDER_PATH` doesn't exist yet. Creating it"
+              mkdir -p "$SUBFOLDER_PATH"
+          fi
+        env:
+          SUBFOLDER_PATH: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}
+      
+      - name: Download `complete_docs` artifact to the subfolder
+        uses: actions/download-artifact@v4 
+        with:
+          name: complete_docs
+          path: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}
         
-            - name: Install Rust toolchain
-              uses: actions-rust-lang/setup-rust-toolchain@v1 
+      - name: Stage and commit the changes (if there are any) to `hotstuff_rs_docs`
+        id: commit_changes
+        run: |
+          git diff --exit-code
+          git_diff_exit_code=$?
 
-            - name: Generate complete rustdocs 
-              run: cargo doc --document-private-items --no-deps 
+          # If there are changes to the Rustdocs, then commit these changes.
+          if [ $git_diff_exit_code -eq 1 ]; then
+            echo "docs_changed=true" >> $GITHUB_OUTPUT
+            git config --global user.name "github-actions[bot]"
+            git config --global user.email "github-actions[bot]@users.noreply.github.com"
+            git add .
+            git commit -a -m "$COMMIT_MESSAGE"
 
-            - name: Upload rustdocs as `complete_docs` artifact
-              uses: actions/upload-artifact@v4
-              with:
-                name: complete_docs
-                path: target/doc/
+          # If there are no changes to the Rustdocs, skip the next (push) step.
+          elif [ $git_diff_exit_code -eq 0 ]; then
+            echo "The Rustdocs weren't changed, so we should skip the next (push) step."
+            echo "docs_changed=false" >> $GITHUB_OUTPUT
 
-    push_docs:
-        name: Push rustdocs to `hotstuff_rs_docs` repository
-        runs-on: ubuntu-latest
-        needs: build_docs
-        steps:
-            - name: Checkout latest `hotstuff_rs_docs`
-              uses: actions/checkout@v4
-              with:
-                repository: parallelchain-io/hotstuff_rs_docs
-                fetch-depth: 0
-                token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}
+          # If something unexpected happened during 'git diff', fail the job and therefore the workflow.
+          else
+            echo "unhandled error when executing 'git diff'"
+            exit 1
+          fi
+          
+        env: 
+          COMMIT_MESSAGE: "add docs for branch/release `${{ github.ref }}`"
 
-            - name: Compute path to the subfolder the docs should be in 
-              id: compute_subfolder_path
-              run: |
-                subfolder_path=$GITHUB_REF_TYPE/$GITHUB_REF_NAME/
-                echo "subfolder_path=$subfolder_path" >> $GITHUB_OUTPUT
-              env:
-                  GITHUB_REF_TYPE: "${{ github.ref_type }}"
-                  GITHUB_REF_NAME: "${{ github.ref_name }}"
-
-            - name: Prepare the subfolder
-              run: |
-                if [ -d $SUBFOLDER_PATH ]; then
-                    echo "Subfolder `$SUB_FOLDER_PATH` already exists, clearing its contents"
-                    rm -rf "${SUBFOLDER_PATH:?}/"*
-                else
-                    echo "Subfolder `$SUBFOLDER_PATH` doesn't exist yet. Creating it"
-                    mkdir -p "$SUBFOLDER_PATH"
-                fi
-              env:
-                SUBFOLDER_PATH: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}
-            
-            - name: Download `complete_docs` artifact to the subfolder
-              uses: actions/download-artifact@v4 
-              with:
-                name: complete_docs
-                path: ${{ steps.compute_subfolder_path.outputs.subfolder_path }}
-              
-            - name: Stage and commit the changes (if there are any) to `hotstuff_rs_docs`
-              id: commit_changes
-              run: |
-                git diff --exit-code
-                git_diff_exit_code=$?
-
-                # If there are changes to the Rustdocs, then commit these changes.
-                if [ $git_diff_exit_code -eq 1 ]; then
-                  echo "docs_changed=true" >> $GITHUB_OUTPUT
-                  git config --global user.name "github-actions[bot]"
-                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
-                  git add .
-                  git commit -a -m "$COMMIT_MESSAGE"
-
-                # If there are no changes to the Rustdocs, skip the next (push) step.
-                elif [ $git_diff_exit_code -eq 0 ]; then
-                  echo "docs_changed=false" >> $GITHUB_OUTPUT
-
-                # If something unexpected happened during 'git diff', fail the job and therefore the workflow.
-                else
-                  echo "unhandled error when executing 'git diff'"
-                  exit 1
-                fi
-                
-              env: 
-                COMMIT_MESSAGE: "add docs for branch/release `${{ github.ref }}`"
-
-            - if: ${{ steps.commit_changes.outputs.docs_changed == 'true' }}
-              name: Push the changes to `hotstuff_rs_docs` to the remote
-              uses: ad-m/github-push-action@master
-              with:
-                github_token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}
-                repository: parallelchain-io/hotstuff_rs_docs
+      - if: ${{ steps.commit_changes.outputs.docs_changed == 'true' }}
+        name: If there were changes to the Rustdocs, push them to the remote
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.HOTSTUFF_RS_DOCS_PUSHER }}
+          repository: parallelchain-io/hotstuff_rs_docs
